version: '3.7'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8001:8000'
      - '8021:8020'
    depends_on:
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: '127.0.0.1:5001'
      ethereum: 'olympus:https://rpc-tracing.polis.tech'
      GRAPH_LOG: debug
    restart: always
  postgres:
    image: postgres:13
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always